services:
  zmk-build-stable:
    image: zmkfirmware/zmk-build-arm:3.5
    working_dir: /workspace
    entrypoint:
      - python3
      - scripts/build_runner.py
      - build-many
      - --profile
      - stable
    volumes:
      - .:/workspace
      - ./.build/local/workspace:/tmp/zmk-config

  zmk-build-canary:
    image: zmkfirmware/zmk-build-arm:4.1-branch
    working_dir: /workspace
    entrypoint:
      - python3
      - scripts/build_runner.py
      - build-many
      - --profile
      - canary
    volumes:
      - .:/workspace
      - ./.build/local/workspace-main:/tmp/zmk-config-main
