

# --- DISPLAY SETTINGS ---

# enable display
CONFIG_ZMK_DISPLAY=y
# custom status screen (nice-view-gem)
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
# turn off gem animation to save battery
CONFIG_NICE_VIEW_GEM_ANIMATION=n
